/* automatically generated by JSCoverage - do not edit */
if (typeof _$jscoverage === 'undefined') _$jscoverage = {};
if (! _$jscoverage['js/override.js']) {
  _$jscoverage['js/override.js'] = [];
  _$jscoverage['js/override.js'][6] = 0;
}
_$jscoverage['js/override.js'][6]++;
overRide = (function () {
});
_$jscoverage['js/override.js'].source = ["/*"," * Placeholder for android/js/override.js"," * or ios/js/override.js to be included at build time"," */",""," overRide = function(){};"];
