/* automatically generated by JSCoverage - do not edit */
if (typeof _$jscoverage === 'undefined') _$jscoverage = {};
if (! _$jscoverage['js/prefs.js']) {
  _$jscoverage['js/prefs.js'] = [];
  _$jscoverage['js/prefs.js'][5] = 0;
  _$jscoverage['js/prefs.js'][6] = 0;
  _$jscoverage['js/prefs.js'][7] = 0;
  _$jscoverage['js/prefs.js'][17] = 0;
  _$jscoverage['js/prefs.js'][18] = 0;
  _$jscoverage['js/prefs.js'][19] = 0;
  _$jscoverage['js/prefs.js'][20] = 0;
  _$jscoverage['js/prefs.js'][21] = 0;
  _$jscoverage['js/prefs.js'][22] = 0;
}
_$jscoverage['js/prefs.js'][5]++;
var g_debug = true;
_$jscoverage['js/prefs.js'][6]++;
var g_dummyData = true;
_$jscoverage['js/prefs.js'][7]++;
var g_dev = true;
_$jscoverage['js/prefs.js'][17]++;
log = (function (msg, msg2) {
  _$jscoverage['js/prefs.js'][18]++;
  if (g_debug) {
    _$jscoverage['js/prefs.js'][19]++;
    if (msg && msg2) {
      _$jscoverage['js/prefs.js'][20]++;
      console.log(msg, msg2);
    }
    else {
      _$jscoverage['js/prefs.js'][21]++;
      if (msg) {
        _$jscoverage['js/prefs.js'][22]++;
        console.log(msg);
      }
    }
  }
});
_$jscoverage['js/prefs.js'].source = ["/*"," * ---- App Global Variables -----"," */","","var g_debug     = true;\t// true to output excessive logging","var g_dummyData = true;\t// true to use live data, false to use dummy data","var g_dev       = true;\t// true if developing locally","","","/*"," * Custom log function"," * Logging can be easily switched off by"," * setting g_debug to false."," *"," * Accepts 1 or 2 inputs"," */","log = function(msg,msg2){","\tif(g_debug){","\t\tif(msg &amp;&amp; msg2){","\t\t\tconsole.log(msg, msg2);","\t\t} else if(msg){","\t\t\tconsole.log(msg);","\t\t}","\t}","};"];
